sudo: required
services:
  - docker

before_install:
  - docker build -t lakshy/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true lakshy/react-test npm test
after_sucess:
  - docker build -t lakshy/multi-client ./client
  - docker build -t lakshy/multi-server ./server
  - docker build -t lakshy/multi-nginx ./nginx
  - docker build -t lakshy/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password--stdin
  # Take those images and push them to docker hub
  - docker push lakshy/multi-client
  - docker push lakshy/multi-nginx
  - docker push lakshy/multi-server
  - docker push lakshy/multi-worker